# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/MainUI/gui_main.ui'
#
# Created: Sun Aug 31 22:43:41 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(669, 490)
        MainWindow.setMinimumSize(QtCore.QSize(540, 450))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 111, 17))
        self.label.setStyleSheet(_fromUtf8("font: bold;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.DetectionOptionsGroup = QtGui.QGroupBox(self.centralwidget)
        self.DetectionOptionsGroup.setEnabled(False)
        self.DetectionOptionsGroup.setGeometry(QtCore.QRect(320, 300, 290, 90))
        self.DetectionOptionsGroup.setObjectName(_fromUtf8("DetectionOptionsGroup"))
        self.PostRecordingTime_LineEdit_old = QtGui.QLineEdit(self.DetectionOptionsGroup)
        self.PostRecordingTime_LineEdit_old.setGeometry(QtCore.QRect(190, 50, 60, 27))
        self.PostRecordingTime_LineEdit_old.setObjectName(_fromUtf8("PostRecordingTime_LineEdit_old"))
        self.PreRecordingTime_LineEdit = QtGui.QLineEdit(self.DetectionOptionsGroup)
        self.PreRecordingTime_LineEdit.setGeometry(QtCore.QRect(10, 50, 60, 27))
        self.PreRecordingTime_LineEdit.setObjectName(_fromUtf8("PreRecordingTime_LineEdit"))
        self.label_11 = QtGui.QLabel(self.DetectionOptionsGroup)
        self.label_11.setGeometry(QtCore.QRect(190, 30, 90, 17))
        self.label_11.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_7 = QtGui.QLabel(self.DetectionOptionsGroup)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 80, 17))
        self.label_7.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.DetectionOptionsGroup)
        self.label_6.setGeometry(QtCore.QRect(100, 30, 60, 17))
        self.label_6.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.RecordingTime_LineEdit_Old = QtGui.QLineEdit(self.DetectionOptionsGroup)
        self.RecordingTime_LineEdit_Old.setGeometry(QtCore.QRect(100, 50, 60, 27))
        self.RecordingTime_LineEdit_Old.setObjectName(_fromUtf8("RecordingTime_LineEdit_Old"))
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(290, 30, 230, 17))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 66, 17))
        self.label_2.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.disconnectButton = QtGui.QPushButton(self.centralwidget)
        self.disconnectButton.setEnabled(False)
        self.disconnectButton.setGeometry(QtCore.QRect(10, 40, 98, 27))
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setGeometry(QtCore.QRect(530, 450, 121, 27))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.batteryBar = QtGui.QProgressBar(self.centralwidget)
        self.batteryBar.setEnabled(True)
        self.batteryBar.setGeometry(QtCore.QRect(140, 30, 118, 23))
        self.batteryBar.setProperty("value", 0)
        self.batteryBar.setObjectName(_fromUtf8("batteryBar"))
        self.connectButton = QtGui.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 70, 650, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.TimingOptionsGroup = QtGui.QGroupBox(self.centralwidget)
        self.TimingOptionsGroup.setEnabled(False)
        self.TimingOptionsGroup.setGeometry(QtCore.QRect(10, 90, 290, 80))
        self.TimingOptionsGroup.setObjectName(_fromUtf8("TimingOptionsGroup"))
        self.NumberOfTrials_LineEdit = QtGui.QLineEdit(self.TimingOptionsGroup)
        self.NumberOfTrials_LineEdit.setGeometry(QtCore.QRect(10, 240, 110, 27))
        self.NumberOfTrials_LineEdit.setObjectName(_fromUtf8("NumberOfTrials_LineEdit"))
        self.label_10 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 131, 17))
        self.label_10.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Sessions_RadioButton_2 = QtGui.QRadioButton(self.TimingOptionsGroup)
        self.Sessions_RadioButton_2.setEnabled(False)
        self.Sessions_RadioButton_2.setGeometry(QtCore.QRect(10, 130, 170, 22))
        self.Sessions_RadioButton_2.setObjectName(_fromUtf8("Sessions_RadioButton_2"))
        self.Profile_RadioButton_2 = QtGui.QRadioButton(self.TimingOptionsGroup)
        self.Profile_RadioButton_2.setGeometry(QtCore.QRect(10, 110, 170, 22))
        self.Profile_RadioButton_2.setChecked(True)
        self.Profile_RadioButton_2.setObjectName(_fromUtf8("Profile_RadioButton_2"))
        self.label_20 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_20.setGeometry(QtCore.QRect(10, 90, 160, 17))
        self.label_20.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.BlankTime_LineEdit = QtGui.QLineEdit(self.TimingOptionsGroup)
        self.BlankTime_LineEdit.setGeometry(QtCore.QRect(10, 180, 50, 27))
        self.BlankTime_LineEdit.setObjectName(_fromUtf8("BlankTime_LineEdit"))
        self.label_8 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_8.setGeometry(QtCore.QRect(70, 160, 50, 17))
        self.label_8.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.PostRecordingTime_LineEdit = QtGui.QLineEdit(self.TimingOptionsGroup)
        self.PostRecordingTime_LineEdit.setGeometry(QtCore.QRect(190, 180, 50, 27))
        self.PostRecordingTime_LineEdit.setObjectName(_fromUtf8("PostRecordingTime_LineEdit"))
        self.RecordingTime_LineEdit = QtGui.QLineEdit(self.TimingOptionsGroup)
        self.RecordingTime_LineEdit.setGeometry(QtCore.QRect(130, 180, 50, 27))
        self.RecordingTime_LineEdit.setObjectName(_fromUtf8("RecordingTime_LineEdit"))
        self.SteadyTime_LineEdit = QtGui.QLineEdit(self.TimingOptionsGroup)
        self.SteadyTime_LineEdit.setGeometry(QtCore.QRect(70, 180, 50, 27))
        self.SteadyTime_LineEdit.setObjectName(_fromUtf8("SteadyTime_LineEdit"))
        self.label_18 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_18.setGeometry(QtCore.QRect(250, 180, 40, 17))
        self.label_18.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_16 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_16.setGeometry(QtCore.QRect(130, 160, 60, 17))
        self.label_16.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_21 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_21.setGeometry(QtCore.QRect(190, 160, 90, 17))
        self.label_21.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_19 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_19.setGeometry(QtCore.QRect(10, 160, 50, 17))
        self.label_19.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.Classifiers_ComboBox = QtGui.QComboBox(self.TimingOptionsGroup)
        self.Classifiers_ComboBox.setGeometry(QtCore.QRect(10, 50, 230, 27))
        self.Classifiers_ComboBox.setObjectName(_fromUtf8("Classifiers_ComboBox"))
        self.label_9 = QtGui.QLabel(self.TimingOptionsGroup)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_9.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.TrainingFile_Group = QtGui.QGroupBox(self.centralwidget)
        self.TrainingFile_Group.setEnabled(False)
        self.TrainingFile_Group.setGeometry(QtCore.QRect(300, 90, 380, 160))
        self.TrainingFile_Group.setObjectName(_fromUtf8("TrainingFile_Group"))
        self.TrainingFile_ComboBox = QtGui.QComboBox(self.TrainingFile_Group)
        self.TrainingFile_ComboBox.setGeometry(QtCore.QRect(20, 130, 340, 27))
        self.TrainingFile_ComboBox.setObjectName(_fromUtf8("TrainingFile_ComboBox"))
        self.Sessions_RadioButton = QtGui.QRadioButton(self.TrainingFile_Group)
        self.Sessions_RadioButton.setGeometry(QtCore.QRect(200, 50, 130, 22))
        self.Sessions_RadioButton.setObjectName(_fromUtf8("Sessions_RadioButton"))
        self.label_15 = QtGui.QLabel(self.TrainingFile_Group)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 170, 17))
        self.label_15.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.Sessions_ComboBox = QtGui.QComboBox(self.TrainingFile_Group)
        self.Sessions_ComboBox.setEnabled(False)
        self.Sessions_ComboBox.setGeometry(QtCore.QRect(200, 70, 164, 27))
        self.Sessions_ComboBox.setObjectName(_fromUtf8("Sessions_ComboBox"))
        self.Profile_RadioButton = QtGui.QRadioButton(self.TrainingFile_Group)
        self.Profile_RadioButton.setEnabled(False)
        self.Profile_RadioButton.setGeometry(QtCore.QRect(20, 50, 121, 22))
        self.Profile_RadioButton.setChecked(False)
        self.Profile_RadioButton.setObjectName(_fromUtf8("Profile_RadioButton"))
        self.Profile_ComboBox = QtGui.QComboBox(self.TrainingFile_Group)
        self.Profile_ComboBox.setEnabled(False)
        self.Profile_ComboBox.setGeometry(QtCore.QRect(20, 70, 170, 27))
        self.Profile_ComboBox.setObjectName(_fromUtf8("Profile_ComboBox"))
        self.label_17 = QtGui.QLabel(self.TrainingFile_Group)
        self.label_17.setGeometry(QtCore.QRect(20, 110, 131, 17))
        self.label_17.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.connectButton, self.disconnectButton)
        MainWindow.setTabOrder(self.disconnectButton, self.NumberOfTrials_LineEdit)
        MainWindow.setTabOrder(self.NumberOfTrials_LineEdit, self.PreRecordingTime_LineEdit)
        MainWindow.setTabOrder(self.PreRecordingTime_LineEdit, self.RecordingTime_LineEdit_Old)
        MainWindow.setTabOrder(self.RecordingTime_LineEdit_Old, self.PostRecordingTime_LineEdit_old)
        MainWindow.setTabOrder(self.PostRecordingTime_LineEdit_old, self.Classifiers_ComboBox)
        MainWindow.setTabOrder(self.Classifiers_ComboBox, self.startButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Braingizer Detector", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Status</p></body></html>", None))
        self.DetectionOptionsGroup.setTitle(_translate("MainWindow", "Detection Options", None))
        self.PostRecordingTime_LineEdit_old.setText(_translate("MainWindow", "4", None))
        self.PreRecordingTime_LineEdit.setText(_translate("MainWindow", "4", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Post-Record</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Pre-Record</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Record</p></body></html>", None))
        self.RecordingTime_LineEdit_Old.setText(_translate("MainWindow", "4", None))
        self.statusLabel.setText(_translate("MainWindow", "Not Connected", None))
        self.label_2.setText(_translate("MainWindow", "Battery", None))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect", None))
        self.startButton.setText(_translate("MainWindow", "Start Detection", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.TimingOptionsGroup.setTitle(_translate("MainWindow", "Detection Options", None))
        self.NumberOfTrials_LineEdit.setText(_translate("MainWindow", "20", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Number of trials</p></body></html>", None))
        self.Sessions_RadioButton_2.setText(_translate("MainWindow", "Let the user decide", None))
        self.Profile_RadioButton_2.setText(_translate("MainWindow", "Force direction", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Recording Method</p></body></html>", None))
        self.BlankTime_LineEdit.setText(_translate("MainWindow", "2", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Steady</p></body></html>", None))
        self.PostRecordingTime_LineEdit.setText(_translate("MainWindow", "4", None))
        self.RecordingTime_LineEdit.setText(_translate("MainWindow", "4", None))
        self.SteadyTime_LineEdit.setText(_translate("MainWindow", "1", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:sub;\">seconds</span></p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Record</p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Post-Record</p></body></html>", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Blank</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Classifier Script</p></body></html>", None))
        self.TrainingFile_Group.setTitle(_translate("MainWindow", "Training File", None))
        self.Sessions_RadioButton.setText(_translate("MainWindow", "Session Name", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Select by</p></body></html>", None))
        self.Profile_RadioButton.setText(_translate("MainWindow", "Profile Name", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Training File</p></body></html>", None))

