# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/TrainUI/gui_train.ui'
#
# Created: Wed Jul 16 11:20:14 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TrainWindow(object):
    def setupUi(self, TrainWindow):
        TrainWindow.setObjectName(_fromUtf8("TrainWindow"))
        TrainWindow.resize(810, 600)
        TrainWindow.setMinimumSize(QtCore.QSize(810, 600))
        self.centralwidget = QtGui.QWidget(TrainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.untoggleIcon = QtGui.QLabel(self.centralwidget)
        self.untoggleIcon.setGeometry(QtCore.QRect(770, 10, 24, 24))
        self.untoggleIcon.setText(_fromUtf8(""))
        self.untoggleIcon.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/Icon_Untoggled.png")))
        self.untoggleIcon.setObjectName(_fromUtf8("untoggleIcon"))
        self.detalisParent_Frame = QtGui.QFrame(self.centralwidget)
        self.detalisParent_Frame.setGeometry(QtCore.QRect(10, 10, 790, 60))
        self.detalisParent_Frame.setAutoFillBackground(True)
        self.detalisParent_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.detalisParent_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.detalisParent_Frame.setObjectName(_fromUtf8("detalisParent_Frame"))
        self.details_Line = QtGui.QFrame(self.detalisParent_Frame)
        self.details_Line.setGeometry(QtCore.QRect(0, 50, 790, 16))
        self.details_Line.setFrameShape(QtGui.QFrame.HLine)
        self.details_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.details_Line.setObjectName(_fromUtf8("details_Line"))
        self.toggleIcon = QtGui.QLabel(self.detalisParent_Frame)
        self.toggleIcon.setGeometry(QtCore.QRect(760, 0, 24, 24))
        self.toggleIcon.setText(_fromUtf8(""))
        self.toggleIcon.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/Icon_Toggled.png")))
        self.toggleIcon.setObjectName(_fromUtf8("toggleIcon"))
        self.detalisChild_Frame = QtGui.QFrame(self.detalisParent_Frame)
        self.detalisChild_Frame.setGeometry(QtCore.QRect(0, 0, 760, 50))
        self.detalisChild_Frame.setAutoFillBackground(True)
        self.detalisChild_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.detalisChild_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.detalisChild_Frame.setObjectName(_fromUtf8("detalisChild_Frame"))
        self.label_2 = QtGui.QLabel(self.detalisChild_Frame)
        self.label_2.setGeometry(QtCore.QRect(190, 0, 121, 17))
        self.label_2.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Finished_ProgBar = QtGui.QProgressBar(self.detalisChild_Frame)
        self.Finished_ProgBar.setEnabled(True)
        self.Finished_ProgBar.setGeometry(QtCore.QRect(640, 20, 118, 23))
        self.Finished_ProgBar.setProperty("value", 40)
        self.Finished_ProgBar.setObjectName(_fromUtf8("Finished_ProgBar"))
        self.label_4 = QtGui.QLabel(self.detalisChild_Frame)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 111, 17))
        self.label_4.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.NumberOfTrials_Label = QtGui.QLabel(self.detalisChild_Frame)
        self.NumberOfTrials_Label.setGeometry(QtCore.QRect(190, 20, 161, 17))
        self.NumberOfTrials_Label.setObjectName(_fromUtf8("NumberOfTrials_Label"))
        self.label_3 = QtGui.QLabel(self.detalisChild_Frame)
        self.label_3.setGeometry(QtCore.QRect(640, 0, 66, 17))
        self.label_3.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Name_Label = QtGui.QLabel(self.detalisChild_Frame)
        self.Name_Label.setGeometry(QtCore.QRect(0, 20, 161, 17))
        self.Name_Label.setObjectName(_fromUtf8("Name_Label"))
        self.label_6 = QtGui.QLabel(self.detalisChild_Frame)
        self.label_6.setGeometry(QtCore.QRect(350, 0, 120, 17))
        self.label_6.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.EstimatedTime_Label = QtGui.QLabel(self.detalisChild_Frame)
        self.EstimatedTime_Label.setGeometry(QtCore.QRect(350, 20, 110, 17))
        self.EstimatedTime_Label.setObjectName(_fromUtf8("EstimatedTime_Label"))
        self.ClassesNames_Label = QtGui.QLabel(self.detalisChild_Frame)
        self.ClassesNames_Label.setGeometry(QtCore.QRect(500, 20, 90, 17))
        self.ClassesNames_Label.setObjectName(_fromUtf8("ClassesNames_Label"))
        self.label_7 = QtGui.QLabel(self.detalisChild_Frame)
        self.label_7.setGeometry(QtCore.QRect(500, 0, 120, 17))
        self.label_7.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Arrows_Frame = QtGui.QFrame(self.centralwidget)
        self.Arrows_Frame.setGeometry(QtCore.QRect(110, 200, 560, 180))
        self.Arrows_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.Arrows_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Arrows_Frame.setObjectName(_fromUtf8("Arrows_Frame"))
        self.RightArrow = QtGui.QLabel(self.Arrows_Frame)
        self.RightArrow.setGeometry(QtCore.QRect(369, 52, 188, 41))
        self.RightArrow.setText(_fromUtf8(""))
        self.RightArrow.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_RightArrow_Grey.png")))
        self.RightArrow.setObjectName(_fromUtf8("RightArrow"))
        self.LeftArrow = QtGui.QLabel(self.Arrows_Frame)
        self.LeftArrow.setGeometry(QtCore.QRect(2, 57, 188, 41))
        self.LeftArrow.setText(_fromUtf8(""))
        self.LeftArrow.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_LeftArrow_Grey.png")))
        self.LeftArrow.setObjectName(_fromUtf8("LeftArrow"))
        self.BwdArrow = QtGui.QLabel(self.Arrows_Frame)
        self.BwdArrow.setGeometry(QtCore.QRect(200, 100, 156, 80))
        self.BwdArrow.setText(_fromUtf8(""))
        self.BwdArrow.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_BackArrow_Grey.png")))
        self.BwdArrow.setObjectName(_fromUtf8("BwdArrow"))
        self.FwdArrow = QtGui.QLabel(self.Arrows_Frame)
        self.FwdArrow.setGeometry(QtCore.QRect(225, 6, 112, 44))
        self.FwdArrow.setText(_fromUtf8(""))
        self.FwdArrow.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_FWDArrow_Grey.png")))
        self.FwdArrow.setObjectName(_fromUtf8("FwdArrow"))
        self.StopCircle = QtGui.QLabel(self.Arrows_Frame)
        self.StopCircle.setGeometry(QtCore.QRect(234, 59, 85, 33))
        self.StopCircle.setText(_fromUtf8(""))
        self.StopCircle.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_Stop_Grey.png")))
        self.StopCircle.setObjectName(_fromUtf8("StopCircle"))
        self.Welcome_Frame = QtGui.QFrame(self.centralwidget)
        self.Welcome_Frame.setGeometry(QtCore.QRect(100, 180, 580, 280))
        self.Welcome_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.Welcome_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Welcome_Frame.setObjectName(_fromUtf8("Welcome_Frame"))
        self.WelcomeNote_Label = QtGui.QLabel(self.Welcome_Frame)
        self.WelcomeNote_Label.setGeometry(QtCore.QRect(20, 10, 540, 210))
        self.WelcomeNote_Label.setStyleSheet(_fromUtf8("font: bold;"))
        self.WelcomeNote_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.WelcomeNote_Label.setObjectName(_fromUtf8("WelcomeNote_Label"))
        self.Start_Button = QtGui.QPushButton(self.Welcome_Frame)
        self.Start_Button.setGeometry(QtCore.QRect(230, 240, 121, 27))
        self.Start_Button.setObjectName(_fromUtf8("Start_Button"))
        self.FinishedNote_Frame = QtGui.QFrame(self.centralwidget)
        self.FinishedNote_Frame.setGeometry(QtCore.QRect(0, 350, 791, 280))
        self.FinishedNote_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.FinishedNote_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.FinishedNote_Frame.setObjectName(_fromUtf8("FinishedNote_Frame"))
        self.FinishedNote_Label = QtGui.QLabel(self.FinishedNote_Frame)
        self.FinishedNote_Label.setGeometry(QtCore.QRect(0, 10, 791, 100))
        self.FinishedNote_Label.setText(_fromUtf8("<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Thank you for your participation.</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Data saved to: </span><span style=\" font-size:10pt;\">TrainingData</span><span style=\" font-size:10pt; font-weight:600;\">/</span><span style=\" font-size:10pt;\">[Session_Name]</span><span style=\" font-size:10pt; font-weight:600;\">/</span><span style=\" font-size:10pt;\">[FileName].csv</span></p></body></html>"))
        self.FinishedNote_Label.setObjectName(_fromUtf8("FinishedNote_Label"))
        self.AddComments_Button = QtGui.QPushButton(self.FinishedNote_Frame)
        self.AddComments_Button.setGeometry(QtCore.QRect(290, 210, 200, 27))
        self.AddComments_Button.setObjectName(_fromUtf8("AddComments_Button"))
        self.Comments_LineEdit = QtGui.QLineEdit(self.FinishedNote_Frame)
        self.Comments_LineEdit.setGeometry(QtCore.QRect(220, 170, 350, 27))
        self.Comments_LineEdit.setObjectName(_fromUtf8("Comments_LineEdit"))
        self.label_17 = QtGui.QLabel(self.FinishedNote_Frame)
        self.label_17.setGeometry(QtCore.QRect(220, 150, 321, 17))
        self.label_17.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.Clipboard_Button = QtGui.QPushButton(self.FinishedNote_Frame)
        self.Clipboard_Button.setGeometry(QtCore.QRect(300, 100, 180, 27))
        self.Clipboard_Button.setObjectName(_fromUtf8("Clipboard_Button"))
        self.Arrows_Frame_Normal = QtGui.QFrame(self.centralwidget)
        self.Arrows_Frame_Normal.setGeometry(QtCore.QRect(210, 70, 370, 110))
        self.Arrows_Frame_Normal.setFrameShape(QtGui.QFrame.NoFrame)
        self.Arrows_Frame_Normal.setFrameShadow(QtGui.QFrame.Raised)
        self.Arrows_Frame_Normal.setObjectName(_fromUtf8("Arrows_Frame_Normal"))
        self.RightArrow_Normal = QtGui.QLabel(self.Arrows_Frame_Normal)
        self.RightArrow_Normal.setGeometry(QtCore.QRect(215, 0, 155, 110))
        self.RightArrow_Normal.setText(_fromUtf8(""))
        self.RightArrow_Normal.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_RightArrow_Normal_Grey.png")))
        self.RightArrow_Normal.setObjectName(_fromUtf8("RightArrow_Normal"))
        self.LeftArrow_Normal = QtGui.QLabel(self.Arrows_Frame_Normal)
        self.LeftArrow_Normal.setGeometry(QtCore.QRect(0, 0, 155, 110))
        self.LeftArrow_Normal.setText(_fromUtf8(""))
        self.LeftArrow_Normal.setPixmap(QtGui.QPixmap(_fromUtf8("Resources/IMGs/TrainUI_LeftArrow_Normal_Grey.png")))
        self.LeftArrow_Normal.setObjectName(_fromUtf8("LeftArrow_Normal"))
        TrainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainWindow)

    def retranslateUi(self, TrainWindow):
        TrainWindow.setWindowTitle(_translate("TrainWindow", "Braingizer Trainer - Training Session", None))
        self.label_2.setText(_translate("TrainWindow", "<html><head/><body><p>Number of Trials</p></body></html>", None))
        self.label_4.setText(_translate("TrainWindow", "<html><head/><body><p>Name</p></body></html>", None))
        self.NumberOfTrials_Label.setText(_translate("TrainWindow", "<html><head/><body><p> 0/150 <span style=\" color:#9a9a9a;\">(50x3)</span></p></body></html>", None))
        self.label_3.setText(_translate("TrainWindow", "Finished", None))
        self.Name_Label.setText(_translate("TrainWindow", "Mohamed Nour El-Din", None))
        self.label_6.setText(_translate("TrainWindow", "<html><head/><body><p>Time Remaining</p></body></html>", None))
        self.EstimatedTime_Label.setText(_translate("TrainWindow", "4 min", None))
        self.ClassesNames_Label.setText(_translate("TrainWindow", "R, L, B, F & N", None))
        self.label_7.setText(_translate("TrainWindow", "Classes Names", None))
        self.WelcomeNote_Label.setText(_translate("TrainWindow", "<html><head/><body><p align=\"justify\">Welcome [Name],</p><p align=\"justify\"><span style=\" font-weight:400;\">Kindly set in a comfortable chair with armrests.</span></p><p align=\"justify\"><span style=\" font-weight:400;\">You will have a number of </span>[nn]<span style=\" font-weight:400;\"> trials for </span>[n]<span style=\" font-weight:400;\"> classes:</span></p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li>[Class]</li><li>[Class]</li><li>[Class]</li><li>[Class]</li><li>[Class]</li></ul><p align=\"justify\"><span style=\" font-weight:400;\">Thank you for your participation, click the start button whenever you are ready.</span></p></body></html>", None))
        self.Start_Button.setText(_translate("TrainWindow", "Start Training", None))
        self.AddComments_Button.setText(_translate("TrainWindow", "Save Comments and Close", None))
        self.label_17.setText(_translate("TrainWindow", "<html><head/><body><p>Comment on this session:<span style=\" color:#9f9f9f;\"> (Optional)</span></p></body></html>", None))
        self.Clipboard_Button.setText(_translate("TrainWindow", "Copy path to clipboard", None))

