# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/MainUI/gui_main.ui'
#
# Created: Wed Jul 16 11:20:14 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(540, 569)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(540, 615))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 10, 111, 17))
        self.label.setStyleSheet(_fromUtf8("font: bold;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.Status_Label = QtGui.QLabel(self.centralwidget)
        self.Status_Label.setGeometry(QtCore.QRect(340, 30, 380, 17))
        self.Status_Label.setObjectName(_fromUtf8("Status_Label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 66, 17))
        self.label_2.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Disconnect_Button = QtGui.QPushButton(self.centralwidget)
        self.Disconnect_Button.setEnabled(False)
        self.Disconnect_Button.setGeometry(QtCore.QRect(20, 40, 98, 27))
        self.Disconnect_Button.setObjectName(_fromUtf8("Disconnect_Button"))
        self.Start_Button = QtGui.QPushButton(self.centralwidget)
        self.Start_Button.setEnabled(False)
        self.Start_Button.setGeometry(QtCore.QRect(400, 520, 121, 27))
        self.Start_Button.setObjectName(_fromUtf8("Start_Button"))
        self.Battery_ProgBar = QtGui.QProgressBar(self.centralwidget)
        self.Battery_ProgBar.setEnabled(True)
        self.Battery_ProgBar.setGeometry(QtCore.QRect(170, 30, 118, 23))
        self.Battery_ProgBar.setProperty("value", 0)
        self.Battery_ProgBar.setObjectName(_fromUtf8("Battery_ProgBar"))
        self.Connect_Button = QtGui.QPushButton(self.centralwidget)
        self.Connect_Button.setGeometry(QtCore.QRect(20, 10, 98, 27))
        self.Connect_Button.setObjectName(_fromUtf8("Connect_Button"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 520, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.SessionDetails_Group = QtGui.QGroupBox(self.centralwidget)
        self.SessionDetails_Group.setEnabled(False)
        self.SessionDetails_Group.setGeometry(QtCore.QRect(20, 110, 541, 230))
        self.SessionDetails_Group.setObjectName(_fromUtf8("SessionDetails_Group"))
        self.Sessions_ComboBox = QtGui.QComboBox(self.SessionDetails_Group)
        self.Sessions_ComboBox.setGeometry(QtCore.QRect(20, 50, 211, 27))
        self.Sessions_ComboBox.setObjectName(_fromUtf8("Sessions_ComboBox"))
        self.Sessions_ComboBox.addItem(_fromUtf8(""))
        self.label_18 = QtGui.QLabel(self.SessionDetails_Group)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 81, 17))
        self.label_18.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.SessionSub1_Group = QtGui.QGroupBox(self.SessionDetails_Group)
        self.SessionSub1_Group.setGeometry(QtCore.QRect(20, 90, 220, 140))
        self.SessionSub1_Group.setTitle(_fromUtf8(""))
        self.SessionSub1_Group.setObjectName(_fromUtf8("SessionSub1_Group"))
        self.label_21 = QtGui.QLabel(self.SessionSub1_Group)
        self.label_21.setGeometry(QtCore.QRect(0, 0, 111, 17))
        self.label_21.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Description_TextEdit = QtGui.QTextEdit(self.SessionSub1_Group)
        self.Description_TextEdit.setGeometry(QtCore.QRect(0, 20, 211, 120))
        self.Description_TextEdit.setObjectName(_fromUtf8("Description_TextEdit"))
        self.SessionSub2_Group = QtGui.QGroupBox(self.SessionDetails_Group)
        self.SessionSub2_Group.setGeometry(QtCore.QRect(280, 30, 220, 200))
        self.SessionSub2_Group.setTitle(_fromUtf8(""))
        self.SessionSub2_Group.setObjectName(_fromUtf8("SessionSub2_Group"))
        self.BlankTime_LineEdit = QtGui.QLineEdit(self.SessionSub2_Group)
        self.BlankTime_LineEdit.setGeometry(QtCore.QRect(0, 80, 50, 27))
        self.BlankTime_LineEdit.setObjectName(_fromUtf8("BlankTime_LineEdit"))
        self.label_6 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_6.setGeometry(QtCore.QRect(60, 60, 50, 17))
        self.label_6.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.NumberOfTrials_LineEdit = QtGui.QLineEdit(self.SessionSub2_Group)
        self.NumberOfTrials_LineEdit.setGeometry(QtCore.QRect(0, 20, 211, 27))
        self.NumberOfTrials_LineEdit.setObjectName(_fromUtf8("NumberOfTrials_LineEdit"))
        self.SteadyTime_LineEdit = QtGui.QLineEdit(self.SessionSub2_Group)
        self.SteadyTime_LineEdit.setGeometry(QtCore.QRect(60, 80, 50, 27))
        self.SteadyTime_LineEdit.setObjectName(_fromUtf8("SteadyTime_LineEdit"))
        self.label_8 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 210, 17))
        self.label_8.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_10.setGeometry(QtCore.QRect(180, 80, 40, 17))
        self.label_10.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_7 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_7.setGeometry(QtCore.QRect(0, 60, 50, 17))
        self.label_7.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.TrainingTime_LineEdit = QtGui.QLineEdit(self.SessionSub2_Group)
        self.TrainingTime_LineEdit.setGeometry(QtCore.QRect(120, 80, 50, 27))
        self.TrainingTime_LineEdit.setObjectName(_fromUtf8("TrainingTime_LineEdit"))
        self.label_9 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_9.setGeometry(QtCore.QRect(120, 60, 60, 17))
        self.label_9.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_13 = QtGui.QLabel(self.SessionSub2_Group)
        self.label_13.setGeometry(QtCore.QRect(0, 120, 121, 17))
        self.label_13.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Right_CheckBox = QtGui.QCheckBox(self.SessionSub2_Group)
        self.Right_CheckBox.setGeometry(QtCore.QRect(0, 140, 71, 22))
        self.Right_CheckBox.setChecked(True)
        self.Right_CheckBox.setObjectName(_fromUtf8("Right_CheckBox"))
        self.Back_CheckBox = QtGui.QCheckBox(self.SessionSub2_Group)
        self.Back_CheckBox.setGeometry(QtCore.QRect(120, 160, 100, 22))
        self.Back_CheckBox.setChecked(True)
        self.Back_CheckBox.setObjectName(_fromUtf8("Back_CheckBox"))
        self.Left_CheckBox = QtGui.QCheckBox(self.SessionSub2_Group)
        self.Left_CheckBox.setGeometry(QtCore.QRect(0, 160, 61, 22))
        self.Left_CheckBox.setChecked(True)
        self.Left_CheckBox.setObjectName(_fromUtf8("Left_CheckBox"))
        self.Forward_CheckBox = QtGui.QCheckBox(self.SessionSub2_Group)
        self.Forward_CheckBox.setGeometry(QtCore.QRect(120, 140, 90, 22))
        self.Forward_CheckBox.setChecked(True)
        self.Forward_CheckBox.setObjectName(_fromUtf8("Forward_CheckBox"))
        self.Neutral_CheckBox = QtGui.QCheckBox(self.SessionSub2_Group)
        self.Neutral_CheckBox.setGeometry(QtCore.QRect(0, 180, 110, 22))
        self.Neutral_CheckBox.setChecked(True)
        self.Neutral_CheckBox.setObjectName(_fromUtf8("Neutral_CheckBox"))
        self.PersonalDetails_Group = QtGui.QGroupBox(self.centralwidget)
        self.PersonalDetails_Group.setEnabled(False)
        self.PersonalDetails_Group.setGeometry(QtCore.QRect(20, 350, 240, 201))
        self.PersonalDetails_Group.setObjectName(_fromUtf8("PersonalDetails_Group"))
        self.label_14 = QtGui.QLabel(self.PersonalDetails_Group)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 81, 17))
        self.label_14.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Profile_ComboBox = QtGui.QComboBox(self.PersonalDetails_Group)
        self.Profile_ComboBox.setGeometry(QtCore.QRect(20, 50, 211, 27))
        self.Profile_ComboBox.setObjectName(_fromUtf8("Profile_ComboBox"))
        self.Profile_ComboBox.addItem(_fromUtf8(""))
        self.NewProfile_GroupBox = QtGui.QGroupBox(self.PersonalDetails_Group)
        self.NewProfile_GroupBox.setEnabled(False)
        self.NewProfile_GroupBox.setGeometry(QtCore.QRect(10, 90, 221, 110))
        self.NewProfile_GroupBox.setTitle(_fromUtf8(""))
        self.NewProfile_GroupBox.setObjectName(_fromUtf8("NewProfile_GroupBox"))
        self.label_15 = QtGui.QLabel(self.NewProfile_GroupBox)
        self.label_15.setGeometry(QtCore.QRect(130, 60, 81, 17))
        self.label_15.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.NewProfile_GroupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.label_16.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.Age_LineEdit = QtGui.QLineEdit(self.NewProfile_GroupBox)
        self.Age_LineEdit.setGeometry(QtCore.QRect(10, 80, 81, 27))
        self.Age_LineEdit.setObjectName(_fromUtf8("Age_LineEdit"))
        self.Name_LineEdit = QtGui.QLineEdit(self.NewProfile_GroupBox)
        self.Name_LineEdit.setGeometry(QtCore.QRect(10, 20, 211, 27))
        self.Name_LineEdit.setObjectName(_fromUtf8("Name_LineEdit"))
        self.label_17 = QtGui.QLabel(self.NewProfile_GroupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 111, 17))
        self.label_17.setStyleSheet(_fromUtf8("font: bold;"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.Gender_ComboBox = QtGui.QComboBox(self.NewProfile_GroupBox)
        self.Gender_ComboBox.setGeometry(QtCore.QRect(130, 80, 91, 27))
        self.Gender_ComboBox.setObjectName(_fromUtf8("Gender_ComboBox"))
        self.Gender_ComboBox.addItem(_fromUtf8(""))
        self.Gender_ComboBox.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Connect_Button, self.Disconnect_Button)
        MainWindow.setTabOrder(self.Disconnect_Button, self.Sessions_ComboBox)
        MainWindow.setTabOrder(self.Sessions_ComboBox, self.Description_TextEdit)
        MainWindow.setTabOrder(self.Description_TextEdit, self.NumberOfTrials_LineEdit)
        MainWindow.setTabOrder(self.NumberOfTrials_LineEdit, self.BlankTime_LineEdit)
        MainWindow.setTabOrder(self.BlankTime_LineEdit, self.SteadyTime_LineEdit)
        MainWindow.setTabOrder(self.SteadyTime_LineEdit, self.TrainingTime_LineEdit)
        MainWindow.setTabOrder(self.TrainingTime_LineEdit, self.Right_CheckBox)
        MainWindow.setTabOrder(self.Right_CheckBox, self.Left_CheckBox)
        MainWindow.setTabOrder(self.Left_CheckBox, self.Neutral_CheckBox)
        MainWindow.setTabOrder(self.Neutral_CheckBox, self.Forward_CheckBox)
        MainWindow.setTabOrder(self.Forward_CheckBox, self.Back_CheckBox)
        MainWindow.setTabOrder(self.Back_CheckBox, self.Profile_ComboBox)
        MainWindow.setTabOrder(self.Profile_ComboBox, self.Name_LineEdit)
        MainWindow.setTabOrder(self.Name_LineEdit, self.Age_LineEdit)
        MainWindow.setTabOrder(self.Age_LineEdit, self.Gender_ComboBox)
        MainWindow.setTabOrder(self.Gender_ComboBox, self.Start_Button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Braingizer Trainer", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Status</p></body></html>", None))
        self.Status_Label.setText(_translate("MainWindow", "Not Connected", None))
        self.label_2.setText(_translate("MainWindow", "Battery", None))
        self.Disconnect_Button.setText(_translate("MainWindow", "Disconnect", None))
        self.Start_Button.setText(_translate("MainWindow", "Start Training", None))
        self.Connect_Button.setText(_translate("MainWindow", "Connect", None))
        self.SessionDetails_Group.setTitle(_translate("MainWindow", "Session Details", None))
        self.Sessions_ComboBox.setItemText(0, _translate("MainWindow", "<New Session>", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Session</p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Description</p></body></html>", None))
        self.Description_TextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.BlankTime_LineEdit.setText(_translate("MainWindow", "2", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Steady</p></body></html>", None))
        self.NumberOfTrials_LineEdit.setText(_translate("MainWindow", "50", None))
        self.SteadyTime_LineEdit.setText(_translate("MainWindow", "1", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Number of trials <span style=\" font-weight:400;\">(per class)</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:sub;\">seconds</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Blank</p></body></html>", None))
        self.TrainingTime_LineEdit.setText(_translate("MainWindow", "4", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Training</p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Training Classes</p></body></html>", None))
        self.Right_CheckBox.setText(_translate("MainWindow", "Right", None))
        self.Back_CheckBox.setText(_translate("MainWindow", "Back", None))
        self.Left_CheckBox.setText(_translate("MainWindow", "Left", None))
        self.Forward_CheckBox.setText(_translate("MainWindow", "Forward", None))
        self.Neutral_CheckBox.setText(_translate("MainWindow", "Neutral", None))
        self.PersonalDetails_Group.setTitle(_translate("MainWindow", "Personal Details", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Profile</p></body></html>", None))
        self.Profile_ComboBox.setItemText(0, _translate("MainWindow", "<New Profile>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Gender</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Age</p></body></html>", None))
        self.Age_LineEdit.setText(_translate("MainWindow", "0", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Name</p></body></html>", None))
        self.Gender_ComboBox.setItemText(0, _translate("MainWindow", "Male", None))
        self.Gender_ComboBox.setItemText(1, _translate("MainWindow", "Female", None))

